version: '3.9'
services:
  mysql-kc:
    image: mysql:9.0
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev --import-realm
    ports:
      - 8180:8080
    restart: unless-stopped
    build: ../pogos-app/src/main/resources/keycloak
    environment:
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_DB_URL: jdbc:mysql://mysql-kc:3306/keycloak
      KC_FEATURES: token-exchange,admin-fine-grained-authz
#      PROXY_ADDRESS_FORWARDING:
#      KC_PROXY: edge
      KC_HOSTNAME: localhost
#      KC_HOSTNAME_STRICT_HTTPS: 'true'
    networks:
      - keycloak-and-mysql-network
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:

  redis-data:
    driver: local
